apply from: 'gradle/scripts/helpers.gradle'

tasks.register('downloadFile', Download) {
    src 'https://files.vexatos.com/Computronics/Computronics-1.12.2-1.6.6-deobf.jar'
    dest new File(project.rootDir, "libs")
    overwrite false
}

compileJava.dependsOn(downloadFile)

repositories {
    // Other repositories described by default:
    // CleanroomMC: https://maven.cleanroommc.com
    maven {
        name 'CurseMaven'
        url 'https://curse.cleanroommc.com'
    }
    maven {
        name 'Modrinth'
        url 'https://api.modrinth.com/maven'
    }
    flatDir {
        dirs 'libs'
    }
    mavenLocal() // Must be last for caching to work
}


dependencies {
    compileOnly "com.cleanroommc:sponge-mixin:0.20.13+mixin.0.8.7"
    if (propertyBool('enable_lwjglx')) {
        compileOnly "com.cleanroommc:lwjglx:1.0.0"
    }
    compileOnly "curse.maven:glibyvc-296045:3882806" //Gliby's Voice Chat Reloaded
    modCompileOnly ("curse.maven:umc-371784:4975229") //Immersive Railroading
    modImplementation "curse.maven:dynsur-238891:2922489" //Dynamic Surroundings
    //compileOnly "curse.maven:midnight-304881:2727758" //The Midnight
    //compileOnly "mush:themidnight:0.3.5"
    modCompileOnly ("curse.maven:ic2exp-242638:3838713") //IC2 EXP
    modImplementation ("curse.maven:ic2c-242942:8153677") //IC2 Classic
    compileOnly "stub:Computronics:1.12.2-1.6.6:deobf" // Computronics

    modImplementation ("curse.maven:enhancedvisuals-255389:3507523")
    modImplementation ("curse.maven:simple-voice-chat-416089:6697106")

    modCompileOnly ("curse.maven:midnight-304881:2727758")
    
    modImplementation ('curse.maven:jukebox-270542:2443318')

    // Example - Dependency descriptor:
    // 'com.google.code.gson:gson:2.8.6' << group: com.google.code.gson, name:gson, version:2.8.6
    // 'group:name:version:classifier' where classifier is optional

    // Example - CurseMaven dependencies:
    // 'curse.maven:had-enough-items-557549:4543375' << had-enough-items = project slug, 557549 = project id, 4543375 = file id
    // Full documentation: https://cursemaven.com/

    // Example - Modrinth dependencies:
    // 'maven.modrinth:jei:4.16.1.1000' << jei = project name, 4.16.1.1000 = file version
    // Full documentation: https://docs.modrinth.com/docs/tutorials/maven/

    // Common dependency types (configuration):
    // implementation = dependency available at both compile time and runtime
    // runtimeOnly = runtime dependency
    // compileOnly = compile time dependency
    // annotationProcessor = annotation processing dependencies
    // contain = bundle dependency jars into final artifact, will extract them in mod loading. Please only do this to non-mod dependencies.
    // shadow = bundle dependencies into shadow output artifact (relocation configurable in shadowJar task)
    // modImplementation = mod dependency available at both compile time and runtime
    // modCompileOnly = mod dependency available only at compile time

    // Transitive dependencies:
    // (Dependencies that your dependency depends on)
    // If you wish to exclude transitive dependencies in the described dependencies
    // Use a closure as such:
    // implementation ('com.google.code.gson:gson:2.8.6') {
    //     transitive = false
    // }
}
